services:
  sampo-ui: 
    platform: linux/x86_64
    container_name: rocrate-sampo-ui
    build:
      context: .
      dockerfile: docker/sampo-ui/dev.dockerfile
    restart: unless-stopped
    tty: true
    # env_file:
    #   - .env
    # networks:
    #   - web-network
    ports:
      - "8080:8080"
      - "3001:3001"
    volumes:
      - node_modules:/usr/src/app/node_modules/
      - ./frontend/src/configs/rocrate:/usr/src/app/src/configs/rocrate
      - ./frontend/src/client/components/perspectives/rocrate:/usr/src/app/src/client/components/perspectives/rocrate
      - ./frontend/src/client/translations/rocrate:/usr/src/app/src/client/translations/rocrate
      - ./frontend/src/server/sparql/rocrate:/usr/src/app/src/server/sparql/rocrate
      - ./frontend/src/configs/portalConfig.json:/usr/src/app/src/configs/portalConfig.json

  jena-fuseki:
    platform: linux/x86_64
    container_name: rocrate-jena-fuseki
    image: stain/jena-fuseki
    restart: unless-stopped
    tty: true
    ports:
      - "3030:3030"
    volumes:
      - jena-fuseki-data:/fuseki
      - ./fuseki/config.ttl:/fuseki/config.ttl
    # secrets:
    #   - admin_password
    environment:
      ADMIN_PASSWORD: admin
      # ADMIN_PASSWORD_FILE: /run/secrets/admin_password

# secrets:
#   admin_password:
#     file: .docker/secrets/admin_password.txt

# networks:
#   web-network:
#     name: europeanbooks-web-network

volumes:
  jena-fuseki-data:
    name: rocrate-data
  node_modules:
    name: rocrate-node_modules
